### ISSUE TITLE
Configuration for timeout

### ISSUE THREAD

**Issue by malfynnction** [rmehner/bits-to-dead-trees#130]
Currently, the page times out if it doesn't load within 1 minute:
https://github.com/rmehner/bits-to-dead-trees/blob/320b318e1042e52a939abe07dfc4e5c54ae57cb0/index.js#L45

We use bits-to-dead-trees to generate very long PDFs (> 1000 pages), and some of those pages needs significantly longer to load. It would be very helpful if we could configure the timeout option from within our app.

**Comment by rmehner** [comment]
Good point, so far our parameters are:

`url` to pass the url and `options` to pass in the PDF options for Playwright. I kinda regret not calling those `pdf_options`. Would you add a new top level option? Kinda like this:

```json
{
  "url": "https://test.example",
  "options": {
    "landscape": true
  },
  "browser": {
    "timeout": 60000
  }
}
```

Or do you have another idea?

**Comment by malfynnction** [comment]
>  I kinda regret not calling those `pdf_options`.

I mean, you could always rename them? 🤔

But I think `browser` or `browserOptions` would work just as well. 🤷🏼‍♂️

**Comment by rmehner** [comment]
> I mean, you could always rename them? 🤔

Yes, we could also do that, but that would be a breaking change that needs adaption in more places then (which I'm fine with, since so far it's all under our control as far as I know)

We could also make it backwards compatible for the time being, but that's a bit more code. I think for now we could go with `browserOptions`. Wonder if we should also allow `pdfOptions` already, as an alias to `options` which we will then deprecate, so consumers can already adapt the code and later one we can remove `options` entirely in a breaking release.

**Comment by malfynnction** [comment]
That sounds good!

**Comment by malfynnction** [comment]
@rmehner You mentioned that you already started implementing this? Because otherwise I'd start working on this now 🤔

**Comment by rmehner** [comment]
@malfynnction yes, there's a branch that I'd need to finish. Hope I can finish this today.

**Comment by A5308Y** [comment]
This is fixed now right? Please reopen the issue, if I misunderstood.
